config/routes.rb
Rails.application.routes.draw do

  resources :drivers

end

app/models/driver.rb
class Driver < ActiveRecord::Base
  has_one :license
  accepts_nested_attributes_for :license

  def name
    [first_name, last_name].join(' ')
  end

end

app/models/license.rb
class License < ActiveRecord::Base
  belongs_to :driver
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  def index
    @drivers = Driver.all
  end

  def new
    @driver = Driver.new
    @driver.build_license
  end

  def create
    @driver = Driver.new(driver_params)

    if @driver.save
      redirect_to drivers_url
    else
      render 'new'
    end
  end

  def destroy
    @driver = Driver.find(params[:id])
    @driver.destroy
    redirect_to drivers_url
  end

  private

  def driver_params
    params.require(:driver).permit(:first_name, :last_name,
      license_attributes: [:number, :state]
      )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/views/drivers/index.html.erb
<h1>Drivers#index</h1>
<ul>
    <% @drivers.each do |driver| %>
      <li><%= driver.name %>
        <% if driver.license.present? %>
        -
        <%= driver.license.car %>
        -
        <%= driver.license.state %>
        <% end %>
        <%= link_to "Delete", driver_path(driver), method: :delete, data: { confirm: 'Are you sure?' } %>
      </li>
    <% end %>
</ul>

<%= link_to "New Driver", new_driver_path %>

app/views/drivers/new.html.erb
<h1>Drivers#new</h1>

<%= link_to "All Drivers", drivers_path %>

<br><br>

<%= form_for @driver do |f| %>
  <div>
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div>
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
    <%= f.fields_for :license do |license_builder| %>
  <div>
    <%= license_builder.label :number, 'Drivers License' %><br>
    <%= license_builder.text_field :number %>
  </div>
  <div>
    <%= license_builder.label :state %><br>
    <%= license_builder.text_field :state %>
  </div>
  <% end %>
  <br>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Drivers</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>